on:
  schedule:
  - cron: '0 17 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
concurrency: steward
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.repository_owner == 'gitbucket' }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - id: generate_token
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: 2717647
        private-key: ${{ secrets.GITBUCKET_BOT_KEY }}
        owner: ${{ github.repository_owner }}
    - uses: scala-steward-org/scala-steward-action@026472ebc0e1f80577b240b249e3dc1494e7041b # v2.86.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "256891351+gitbucket-bot[bot]@users.noreply.github.com"
        author-name: "gitbucket-bot[bot]"
        repos-file: "repos.md"
